### ISSUE TITLE
How about prefixing css class?

### ISSUE THREAD

**Issue by tsulatsitamim** [jmaczan/basic-vue-chat#10]
When I integrate this component to my app, my css was overwritten by component css. For example:
body element text-align become center.

or I missing something?

**Comment by Stiropor** [comment]
Exactly the same problem, my whole app/website is changed... is there a way to disable inline css?

**Comment by thanhchuongbmd** [comment]
> When I integrate this component to my app, my css was overwritten by component css. For example:
> body element text-align become center.
> 
> or I missing something?

Set css global: body{ text-align: center }

**Comment by ColaCheese** [comment]
I delete the css in the _base.scss

**Comment by jmaczan** [comment]
Hello, 
It would be good to add prefixing css classes. I don't actively maintain this component, so I archive the repository. If you would like to help with maintaining, please let me know.
