### ISSUE TITLE
Simplest way to get a demo running

### ISSUE THREAD

**Issue by ChungMasterFlex** [jmaczan/basic-vue-chat#11]
Assuming you used cli to something like:
```
vue create my-project-name
```

INSTALL PACKAGES <br />
```
npm install vue-moment
npm install sass-loader --save-dev 
npm install --save-dev node-sass 
yarn add core-js
npm install ** not 100% sure this is needed but ran into problems without doing it
npm install --save emoji-mart-vue ** only had to this the second time around
```

COPY FOLDERS <br />
Then in your personal project -  you'll need to literally drag three folders (and their subfolders and  into your project.

1. Copy into your components folder the folder called basic-vue-chat from the github repo it is under src > components > basic-vue-chat (there will 3 folders in there - you need them all) <br />
2. Also into your src folder copy the folder called helpers
3. Into your assets folder copy the folder called scss (it will have files and folders)

USING THE COMPONENT:<br />
```
<template>
  <div class="hello">
    <basic-vue-chat />
  </div>
</template>

<script>
import BasicVueChat from './basic-vue-chat/BasicVueChat.vue'

export default {
  name: 'HelloWorld',
  components: {
    BasicVueChat
  },
  props: {
    msg: String
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>
```

NOTE (this may not happen to you): <br />
Due to some error checking, in the InputField.vue methods, I had to change
```
    // send (event) {
      send () {
```
* This happened in other components and had to do similar send(event) => send()
* In my second try, I had to install 
* In my second try, I also got the following error: 
```
 warning  in ./src/components/basic-vue-chat/messages/MessagesList.vue?vue&type=template&id=a81b6668&scoped=true&

Module Warning (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
```

**Comment by jmaczan** [comment]
Hello,
I don't actively maintain this component, so I archive the repository. If you would like to help with maintaining, please let me know.
