### ISSUE TITLE
<font-awesome-icon> 

### ISSUE THREAD

**Issue by Kaavaal** [jmaczan/basic-vue-chat#13]
Hello, who knows how to fix this error?

Unknown custom element: font-awesome-icon - did you register the component correctly? For recursive components, make sure to provide the "name" option.

I saw one topic in "closed" issues, but that answer doesn't help in this case.

**Comment by jmaczan** [comment]
Hello,
I don't actively maintain this component, so I archive the repository. If you would like to help with maintaining, please let me know.
