### ISSUE TITLE
Duplicate key warning

### ISSUE THREAD

**Issue by ghost** [jmaczan/basic-vue-chat#2]
Sending same text at same time generates a warning in the console.
In **messages/MessagesList.vue** it seems better to use the `index` provided by v-for, instead of the `messageKey()` function

Now:
`      v-for="message in feed"
      :key="messageKey(message)"
`

With index:
`      v-for="(message, index) in feed"
      :key="index"
`

Nice chat, btw

**Comment by jmaczan** [comment]
Hi there,

Good point! :slightly_smiling_face: Fixed and released in 0.3.1.

Thx for your contribution
