### ISSUE TITLE
[Doc] How to override SCSS variables

### ISSUE THREAD

**Issue by ghost** [jmaczan/basic-vue-chat#3]
Can you please add a short example in `README.md` at **Customization->Styling**?

Like how to override `$primary` with a new color

`<style lang="scss">

  // example here

</style>`

**Comment by jmaczan** [comment]
Hi,

Sure, added it to README with example. :slightly_smiling_face:

**Comment by ghost** [comment]
I still cannot override.

This is my App.vue. I expect to see some red in the chat, but nothing changes
I installed node-sass and sass-loader, and the project is a CLI 3. Is there any settings to do?
```
<template>
  <div id="app">
    <basic-vue-chat :new-message="message"/>
  </div>
</template>

<script>
import BasicVueChat from 'basic-vue-chat'

export default {
  name: 'app',
  components: {
    BasicVueChat
  },
  data() {
    return {
      message: {},
    }
  },
}
</script>

<style lang="scss">
$primary: red;
$header-color: red;
$input-background-color: red;
</style>
```

**Comment by jmaczan** [comment]
Hi,
I studied the issue for a while and found out that there's no easy way to provide this kind of overriding scss variables in project. It would demand changing parcel build and additional actions. If you have some free time, feel free to contribute.

Right now you can just override variables by modifying `style` section in `BasicVueChat` component.

**Comment by beedrill** [comment]
Dear Jmaczan. I think Overriding style is very important for a component to be reusable for other projects, if we can't directly override SCSS, please provide some Slots/props so we can customize. Thank you very much.
