### ISSUE TITLE
`authorId` is wrong?

### ISSUE THREAD

**Issue by ZJUGuoShuai** [jmaczan/basic-vue-chat#4]
I tested the [initial feed](https://github.com/jmaczan/basic-vue-chat#initial-data) and it seemed that the `id` is wrong. `Person` should have `id=1`, not `id=0` because I found that you set the default id of "me" as `0` (after examing the source code). Using the example you gave I got the reserved result:

![](https://i.loli.net/2019/03/31/5ca050a283b14.png)

(I'm a chinese student, sorry for my poor English :(

**Comment by jmaczan** [comment]
Hi Guo,

Yes, you're totally right. The `id` in initial feed should be `0` for author. I fixed the README in 0.3.5 version. 

And by the way, Your English is really fine :slightly_smiling_face: 

Thanks for your contribution, feel free also to create PRs and new feature requests :slightly_smiling_face: 

Best,
Jędrzej
