### ISSUE TITLE
Is there a working example of this component working with two users?

### ISSUE THREAD

**Issue by Issabln** [jmaczan/basic-vue-chat#5]

**Comment by Issabln** [comment]
Or how can I get the current component from another browser tab?

**Comment by jmaczan** [comment]
Hi there,

What do you mean by "working"? The serverside and communication with server (for example sockets) you have to implement on your own. :slightly_smiling_face: BasicVueChat is pure Vue component, without server logic. 

I'm not sure what do you mean by "get the current component from another browser tab". Could you explain, please?

Best,
Jędrzej

**Comment by jmaczan** [comment]
I close the issue due to lack of reply.
