### ISSUE TITLE
Production using rollup

### ISSUE THREAD

**Issue by RayChenCode** [jmaczan/basic-vue-chat#6]
How to use `npm run build` that process produced three JS file(esm, min, umd)?
Can it include in `script` tag on HTML like `npm run serve` display?

**Comment by jmaczan** [comment]
Hi Ray,

To be honest, I didn't dive into rollup build so this feature might be unstable. How important is that for you? I guess that you don't want to use chat as a Vue component, but as a module instead?

**Comment by RayChenCode** [comment]
Thanks for your response!

As you said, I not using basic-vue-chat as vue component, just render web in id#app which mount directly for my chat-bot.
In this case, I use `npm run build-legacy`  instead of `npm run build`. 
Now it works good for me :)

**Comment by jmaczan** [comment]
Great, I'm glad that you figured out a solution :slightly_smiling_face: 

I hope you'll be happy of using Basic Vue Chat.

Best,
Jędrzej
