### ISSUE TITLE
Trying to change colors

### ISSUE THREAD

**Issue by hwadii** [jmaczan/basic-vue-chat#8]
Hi, thank you for your wonderful chat app. I'm trying to change the colors and I'm facing an issue. Right now, I have a Vue application which is using Vuetify.js. When I try to change the colors, nothing seem to happen. I'm not using SCSS in my project.

**Comment by hwadii** [comment]
I have figured it out. I didn't read the docs properly. Pardon my newbie question.

**Comment by jmaczan** [comment]
Hello Wadii,

I'm glad that you solved this on your own. :slightly_smiling_face: 

Greetings,
Jędrzej
