### ISSUE TITLE
Unknown custom element: <font-awesome-icon> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

### ISSUE THREAD

**Issue by tsulatsitamim** [jmaczan/basic-vue-chat#9]
i found this error whe use this lib, am I missing something?

**Comment by tsulatsitamim** [comment]
I write 
import { paperclip, smile } from '@fortawesome/free-solid-svg-icons'
intead of
import { faPaperclip, faSmile } from '@fortawesome/free-solid-svg-icons'

**Comment by Kaavaal** [comment]
Hello, any updates on this issue? 
Seems that this error message cannot be fixed by adding additional imports like the comment above.
